// Code generated by MockGen. DO NOT EDIT.
// Source: repos/project/model (interfaces: NewInterface)

// Package mock_model is a generated GoMock package.
package mock_model

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNewInterface is a mock of NewInterface interface.
type MockNewInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNewInterfaceMockRecorder
}

// MockNewInterfaceMockRecorder is the mock recorder for MockNewInterface.
type MockNewInterfaceMockRecorder struct {
	mock *MockNewInterface
}

// NewMockNewInterface creates a new mock instance.
func NewMockNewInterface(ctrl *gomock.Controller) *MockNewInterface {
	mock := &MockNewInterface{ctrl: ctrl}
	mock.recorder = &MockNewInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNewInterface) EXPECT() *MockNewInterfaceMockRecorder {
	return m.recorder
}

// f1 mocks base method.
func (m *MockNewInterface) f1() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "f1")
}

// f1 indicates an expected call of f1.
func (mr *MockNewInterfaceMockRecorder) f1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "f1", reflect.TypeOf((*MockNewInterface)(nil).f1))
}
