services:
  app:
    image: golang:1.19
    command: sh -c "go run main.go"
    ports:
      - 8080:8080
    working_dir: /Project
    volumes:
      - ./:/Project
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root@123
      MYSQL_DB: User

  mysql:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: User


volumes:
  db-data:
